In [14]:
import numpy as np

a =np.array(6)
b =np.array([2,6,8,5])
c= np.array([[2,4,6],[6,6,7]])
d= np.array([[[4,6,7],[4,6,8]],[[5,7,8],[6,7,8]]])

print("zero dimentional:" ,a)
print("1-D:" ,b)
print("2-D:" ,c)
print("3-D:" ,d)

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

zero dimentional: 6
1-D: [2 6 8 5]
2-D: [[2 4 6]
 [6 6 7]]
3-D: [[[4 6 7]
  [4 6 8]]

 [[5 7 8]
  [6 7 8]]]
0
1
2
3


In [15]:
from numpy import random
x = random.randint(100)
y = random.rand()
print(x)
print(y)
arr = random.randint(100, size=(4))
print(arr)

77
0.5137501955540488
[58  6 85 29]


In [16]:
import matplotlib.pylot as plt
x = np.array([0,4])
y = np.array([0,4])

plt.plot(x,y)
plt.show()

ModuleNotFoundError: No module named 'matplotlib.pylot'